# Generated by Django 3.2.7 on 2021-09-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Na bieżąco', 'Na bieżąco'), ('W trakcie', 'W trakacie'), ('Porzucone', 'Porzucone'), ('Skończone', 'Skończone'), ('Planowane', 'Planowane'), ('Wstrzymane', 'Wstrzymane')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Na bieżąco', 'Na bieżąco'), ('W trakcie', 'W trakacie'), ('Porzucone', 'Porzucone'), ('Skończone', 'Skończone'), ('Planowane', 'Planowane'), ('Wstrzymane', 'Wstrzymane')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Na bieżąco', 'Na bieżąco'), ('W trakcie', 'W trakacie'), ('Porzucone', 'Porzucone'), ('Skończone', 'Skończone'), ('Planowane', 'Planowane'), ('Wstrzymane', 'Wstrzymane')], max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otaku_app.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otaku_app.title'),
        ),
    ]
