# Generated by Django 3.2.7 on 2021-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otaku_app', '0002_auto_20210916_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Na bieżąco', 'Na bieżąco'), ('W trakcie', 'W trakcie'), ('Porzucone', 'Porzucone'), ('Skończone', 'Skończone'), ('Planowane', 'Planowane'), ('Wstrzymane', 'Wstrzymane')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('Na bieżąco', 'Na bieżąco'), ('W trakcie', 'W trakcie'), ('Porzucone', 'Porzucone'), ('Skończone', 'Skończone'), ('Planowane', 'Planowane'), ('Wstrzymane', 'Wstrzymane')], max_length=100),
        ),
        migrations.AlterField(
            model_name='title',
            name='status',
            field=models.CharField(choices=[('Na bieżąco', 'Na bieżąco'), ('W trakcie', 'W trakcie'), ('Porzucone', 'Porzucone'), ('Skończone', 'Skończone'), ('Planowane', 'Planowane'), ('Wstrzymane', 'Wstrzymane')], max_length=100),
        ),
    ]
